apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: dockerapp
    type: back-end
spec:
  template:
    metadata:
      name: dockerapp-pod
      labels:
        app: dockerapp
        type: back-end
    spec:
      containers:
        - name: kubertest
          image: adobrynin/dockertest
  replicas: 3
  selector:
    matchLabels:
      type: back-end
